config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :to_do_lists
  resources :calendar
  resources :categories

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :categories, dependent: :destroy
  # has_many_throughはuser.to_do_lists.include?(@category)みたいのが使えるかもと思って入れてみた。後々不要だったら削除しようと思う。_20150403
  has_many :to_do_lists, through: :categories
	has_many :to_do_lists, dependent: :destroy
	attr_accessor :remember_token, :activation_token, :reset_token
    before_save :downcase_email
    before_create :create_activation_digest
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: {minimum: 6}

	# 与えられた文字列のハッシュを返す(テスト環境で使う)
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

  # ランダムなトークンを返す（リメンバーダイジェストにしてブラウザのキャッシュに保存）
	def User.new_token
		SecureRandom.urlsafe_base64
	end

  # 永続的セッションで使用するユーザーをデータベースに保存する。
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	# ブラウザから渡されたトークンがダイジェストと一致したらtrueを返す
	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end

	# ユーザーログインを破棄する
	def forget
		update_attribute(:remember_digest, nil)
	end

  # アカウントを有効にする
	def activate
		update_attribute(:activated, true)
		update_attribute(:activated_at, Time.zone.now)
	end

  # 有効化用のメールを送信する
	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

	# パスワード再設定用のreset_digestを生成する
	def create_reset_digest
		self.reset_token = User.new_token
		update_attribute(:reset_digest, User.digest(reset_token))
		update_attribute(:reset_set_at, Time.zone.now)
	end

  # パスワード再設定メールを送信する
	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end

	# パスワード再設定の期限が切れている場合はtrueを返す。
	def password_reset_expired?
		reset_set_at < 2.hours.ago
	end

	private

	  # メールアドレスを小文字にする
	  def downcase_email
	  	self.email = email.downcase
	  end

	  # activation_tokenからactivation_digestを作成して、モデルに保存
	  def create_activation_digest
	  	self.activation_token = User.new_token
	  	self.activation_digest = User.digest(activation_token)
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    # gravatarでnavbarに画像を表示するためには@userにログイン中のユーザが格納されている必要があるための対応_20160328
    @user = current_user
    @users = User.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
    @to_do_lists = @user.to_do_lists.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
      @user.send_activation_email
  		flash[:info] = "Habitizeにご登録いただき、ありがとうございます！ お送りしたメールからアカウントを有効化してください。"
      Category.create(category_name: "カテゴリ(デフォルト)", user_id: @user.id)
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "パスワードを更新しました。"
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました。"
    redirect_to users_url
  end

  private

	  def user_params
	  	params.require(:user).permit(:email, :password, :password_confirmation)
	  end

    # beforeフィルター

    # 正しいユーザーの作業か確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, option={size: 80})
		if logged_in?
			gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
			size = option[:size]
			gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
			# image_tag(gravatar_url, alt: user.email[/[a-z\d\w\-.]+/,0],class:"gravatar")
			link_to(image_tag(gravatar_url, alt: user.email[/[a-z\d\w\-.]+/,0],class:"gravatar"), to_do_lists_path) 
		else
			link_to(image_tag("wadachi_2_icon.jpg", alt:"wadachi_2_icon.jpg"), "http://www.i-noh.com")
		end
	end
	
end

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size:50 %>
	<%= link_to user.email, user %>
	  | <%= link_to "削除", user, method: :delete, data: {confirm: "削除してよろしいですか"} %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'パスワード・画像変更') %>
<h1>パスワード・画像変更</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
		  <%= render 'shared/error_messages', object: f.object %>

		  <%= f.label :password, "新しいパスワード" %>
		  <%= f.password_field :password, class: 'form-control' %>

		  <%= f.label :password_confirmation, "新しいパスワード（確認）" %>
		  <%= f.password_field :password_confirmation, class: 'form-control' %>

		  <%= f.submit "保存", class: "btn btn-success" %>
		<% end %>

		<div class= "gravatar_edit">
			<%= gravatar_for @user %>
			<a href="http://gravatar.com/emails" target="_blank">画像変更</a>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<%= provide(:title, 'ユーザー管理')%>
<h1>ユーザー管理</h1>

<%= will_paginate %>

<ul class= "users">
	<% @users.each do |user| %>
	  <%= render user %>
	 <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<h1>新規登録</h1>

<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :email, "メールアドレス" %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :password, "パスワード" %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "パスワード確認（再入力）" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "アカウント作成", class: "btn btn-success" %>
		<% end %>

	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.email[/[a-z\d\w\-.]+/,0]) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
		  <h1>
		  	<%= gravatar_for @user %>
		  	<%= @user.email[/[a-z\d\w\-.]+/,0]%>
      </h1>
            <% if current_user.admin? %>
              <h2><%= link_to "ユーザー管理", users_path %></h2>
            <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.to_do_lists.any? %>
    <h3><%= @user.to_do_lists.count %>件のリスト</h3>
    <ol class="to_do_lists">
      <%= render @to_do_lists %>
    </ol>
    <%= will_paginate @to_do_lists %>
    <% end %>
  </div>
</div>