config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :to_do_lists
  resources :calendar
  resources :categories

end

app/models/to_do_list.rb
class ToDoList < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  default_scope -> {order(created_at: :desc)}
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 140 }
  validates :category_id, presence: true
  validates :priority_flg, presence: true
  validate :picture_size

  private

    # アップロード画像のサイズを検証する
    def picture_size
    	if picture.size > 5.megabytes
    		error.add(:picture, "ファイルサイズの上限は5MBです。")
    	end
    end

end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController

	before_action :logged_in_user, only: [:index, :create, :destroy, :show, :update, :edit]
	before_action :correct_user, only: [:destroy, :edit]

	def index
		@user = current_user
		@to_do_lists = @user.to_do_lists.paginate(page: params[:page])
	end

	def create
		@user = current_user
		@to_do_lists = @user.to_do_lists.paginate(page: params[:page])
		@to_do_list = @user.to_do_lists.build(to_do_list_params)
		if @to_do_list.save
			flash[:info] = "ToDoリストが登録されました。"
			redirect_to root_url
		else
			@cids = @user.category_ids
			render 'static_pages/home'
		end
	end

	def show
		@user = current_user
		@cids = @user.category_ids
		@to_do_list = current_user.to_do_lists.find(params[:id])
	end

	def update
	  @to_do_list = current_user.to_do_lists.find(params[:id])
	  if @to_do_list.update_attributes(to_do_list_params)
	    redirect_to root_url
	  else
	    render 'static_pages/home'
	  end
  end

  def edit
    @to_do_list.update_attribute(:ending_flg, 1)
		flash[:info] = "「#{@to_do_list.title}」完了！（全リストから参照できます）"
		redirect_to root_url
  end

	def destroy
		@to_do_list.destroy
		flash[:info] = "ToDoリストを削除しました。"
		redirect_to request.referrer || root_url
	end

	private

	  def to_do_list_params
	  	params.require(:to_do_list).permit(:title, :category_id, :priority_flg, :schedule_sta, :schedule_end, :comment, :ending_flg, :reminder_mail, :picture)
	  end

	  def correct_user
	  	@to_do_list = current_user.to_do_lists.find_by(id: params[:id])
	  	redirect_to root_url if @to_do_list.nil?
	  end
	end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/views/to_do_lists/_to_do_list.html.erb
<% if !to_do_list.ending_flg %>	
	<li id="to_do_list-<%= to_do_list.id %>">
	<!--暫定的にgravatarを取ってくるが、カテゴリカラーに変更したい-->
		<%= link_to gravatar_for(to_do_list.user, size: 50), to_do_list.user %>
		<span class="category">
		  <%= Category.find(to_do_list.category_id).category_name %>
		</span>
		<span class="title title-font">
		  <%= link_to to_do_list.title, to_do_list %>
		</span>
		<span class="content">
		  <%= image_tag to_do_list.picture.url if to_do_list.picture? %>
		</span>
		<span class="timestamp listedlist">
		  <% if !to_do_list.schedule_sta.nil? %>
		  <%= to_do_list.schedule_sta.month %>月<%= to_do_list.schedule_sta.day %>日<%= to_do_list.schedule_sta.hour %>時<%= to_do_list.schedule_sta.min %>分〜 <br>
		  <% end %>
		  <% if current_user?(to_do_list.user)%>
		    <%= link_to 'x 削除', to_do_list, method: :delete, class: "btn btn-danger delbtn", data: {confirm: "削除してよろしいですか？"} %>
		    <%= link_to '完了', edit_to_do_list_path(to_do_list, ending_flg: 1), class: "btn btn-primary compbtn" %>
		  <% end %>
		</span>
		<div class="clear_float"></div>
	</li>
<% end %>

app/views/to_do_lists/index.html.erb
<% provide(:title, '全リスト') %>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>全リスト</h1>

		<%= will_paginate %>

		<ul class="to_do_lists">
		  <% @to_do_lists.each do |list| %>
		    <li>
		      <%= gravatar_for @user, size: 50 %>
		      <span class="category">
				    <%= Category.find(list.category_id).category_name %>
			    </span>
		      <%= link_to list.title, list, class: "title-font" %>
		      <span class="content">
				    <%= image_tag list.picture.url if list.picture? %>
			    </span>
			    <span class="timestamp listedlist">
				    <% if !list.schedule_sta.nil? %>
				      <%= list.schedule_sta.month %>月<%= list.schedule_sta.day %>日<%= list.schedule_sta.hour %>時<%= list.schedule_sta.min %>分〜 <br>
				    <% end %>
				    <% if current_user?(list.user)%>
				      <%= link_to 'x 削除', list, method: :delete, class: "btn btn-danger delbtn", data: {confirm: "削除してよろしいですか？"} %>
				      <% if !list.ending_flg %>
				        <%= link_to '完了', edit_to_do_list_path(list, ending_flg: 1), class: "btn btn-primary compbtn", data: {confirm: "リストから消えますが、よろしいですか？\n（完了一覧に移動します）"} %>
				      <% else %>
				      <p>完了済み</p>
				      <% end %>
				    <% end %>
				  </span>
				<div class="clear_float"></div>

		    </li>
		  <% end %>
		</ul>

		<%= will_paginate %>
	</div>
</div>

app/views/to_do_lists/show.html.erb
<h1><%= @to_do_list.title %></h1>
<div class="pict-show">
  <%= image_tag @to_do_list.picture.url if @to_do_list.picture? %>
</div>

<%= form_for(@to_do_list) do |f| %>

<div class="row">

	<div class="col-md-6 col-md-offset-3">
		
	  <%= render 'shared/error_messages', object: f.object %>
	  <div class="field">

      <%= f.select :category_id, Category.find(@cids).map{|cid| [cid.category_name, cid.id]}, {}, class: "form-control" %>

	    <%= f.text_field :title, class: "form-control", placeholder: @to_do_list.title %>

	    <%= f.text_area :comment, class: "form-control", placeholder: @to_do_list.comment %>

	    <%= f.select :priority_flg, ["優先", "普通", "後で"], {}, class: "form-control priority_flg", :selected => @to_do_list.priority_flg %>

	    <div class="sep"></div>

	    <%= f.label :remember_me, class: "checkbox inline" do %>
		    <h4 class="relocate">日時指定</h4>
		    <%= f.check_box :reminder_mail, id: "to_do_list_reminder_mail", checked: @to_do_list.reminder_mail ? true : false %>
		    <span>開始時間にリマインダメールを送信</span>
	    <% end %>

	    <div class='input-group date datepicker' id="picker">
		    <%= f.text_field :schedule_sta, data: {:date_format => 'YYYY/MM/DD hh:mm'}, class: "form-control", placeholder: @to_do_list.schedule_sta %>
		    <span class="input-group-addon"></span>
	    </div>

	    <div class='input-group date datepicker' id="picker">
		    <%= f.text_field :schedule_end, data: {:date_format => 'YYYY/MM/DD hh:mm'}, class: "form-control", placeholder: @to_do_list.schedule_end %>
		    <span class="input-group-addon"></span>
	    </div>

	    <%= f.submit "更新", class: "btn btn-success" %>

	    <span class="picture">
  	    <%= f.file_field :picture, class: "form-control", accept: 'image/jpeg,image/gif,image/png', placeholder: "ファイルを上書きする" %>
      </span>

      <%= f.label :ending_flg, class: "checkbox inline" do %>
	      <%= f.check_box :ending_flg, id: "to_do_list_ending_flg", checked: @to_do_list.ending_flg ? true : false  %>
	      <span>完了!</span>
      <% end %>

	  </div>

	 </div>

</div>
  
<% end %>