config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :to_do_lists
  resources :calendar
  resources :categories

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.cm-publishing.co.jp/9784844374442/">「自分を変える習慣力」</a>
    by <a href="http://www.cm-publishing.co.jp/">CrossMedia Publishing</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "ハビタイズとは", about_path %></li>
      <li><%= link_to "お問い合わせ", contact_path %></li>
      <li><a href="http://www.cm-publishing.co.jp/pr/">広報より</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Habitize", root_path, id: "logo" %>
    <nav class="collapse navbar-collapse target">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "ヘルプ", help_path %></li>
        <% if logged_in? %>
         <li><%= link_to "全リスト", to_do_lists_path %></li>
         <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">設定<b class="caret"></b></a>
           <ul class="dropdown-menu">
             <li><%= link_to "パスワード・画像変更", edit_user_path(current_user) %></li>
             <li><%= link_to "カテゴリ編集", categories_path %></li>
             <li class="divider"></li>
             <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
           </ul>
         </li>
         <li class="photo_layout"><%= gravatar_for(@user, size: 20) %></li>
        <% else %>
        <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=300" >
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%="#{message_type}"%>">
        <%= message %>
          <button class="close" data-dismiss="alert">&times;</button>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params)if Rails.env.development? %>
  </div>
</body>
</html>